name: DeadPvp
main: net.deadpvp.Main
description: "Le plugin creatif (nul) de dp (encore + nul)"
author: "les gros nul de dev de DP"
version: 1.0
api-version: 1.16
commands:
  dpaccept:
    description: accept
  hub:
    aliases: lobby
  speed:
    usage: "§cUtilisation: /speed [0-10]"
  spawn:
  livrebeta: