name: DeadPvp
main: net.deadpvp.Main
description: "Plugin crea de DeadPvP"
authors: ["Benigne", "Red_Spash", "Arnaud013"]
version: 1.0
api-version: 1.16
depend:
  - ProtocolLib
commands:
  dpaccept:
    description: accept
  hub:
    aliases: lobby
  speed:
    usage: "§cUtilisation: /speed [0-10]"
    permission: "deadpvp.apprenti"
  spawn:
  livrebeta:
  vanish:
    permission: chat.builder
  tpa:
    usage: "§c/tpa <Player>"
  tpyes:
    aliases: tpaccept
  tpno:
    aliases: tprefuse
  nick:
    usage: "§cUtilisation: /nick <pseudo>"
    permission: "deadpvp.constructeur"
  freeze:
    permission: "chat.builder"
  getname:
    usage: "§Utilisation: /getname <pseudo>"
  tpahere:
  invsee:
    permission: "chat.builder"
  ecsee:
    permission: "chat.builder"
  night: